# Generated by Django 5.2.12 on 2026-03-11 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='平均心跳(bpm)')),
                ('blood_oxygen', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='血氧(%)')),
                ('systolic_bp', models.IntegerField(blank=True, null=True, verbose_name='收缩压(mmHg)')),
                ('diastolic_bp', models.IntegerField(blank=True, null=True, verbose_name='舒张压(mmHg)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='体温(℃)')),
                ('blood_sugar', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='空腹血糖(mmol/L)')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='体重(kg)')),
                ('feeling', models.CharField(blank=True, default='', help_text='老人自述今天的身体感觉', max_length=255, verbose_name='今日感觉')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_health', to='elders.elder', verbose_name='老人')),
            ],
            options={
                'verbose_name': '每日健康数据',
                'verbose_name_plural': '每日健康数据',
                'db_table': 'daily_health',
                'ordering': ['-date'],
                'unique_together': {('elder', 'date')},
            },
        ),
    ]
