# Generated by Django 5.2.12 on 2026-03-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='社区名称')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('contact_person', models.CharField(max_length=64, verbose_name='负责人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('description', models.TextField(blank=True, default='', verbose_name='简介')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '社区',
                'verbose_name_plural': '社区',
                'db_table': 'community',
            },
        ),
    ]
