# Generated by Django 5.2.12 on 2026-03-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('health', '健康异常'), ('checkup_missing', '体检未完成')], max_length=32, verbose_name='类型')),
                ('level', models.CharField(choices=[('warning', '警告'), ('critical', '紧急')], default='warning', max_length=16, verbose_name='级别')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('detail', models.TextField(verbose_name='详情')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('resolved', '已处理')], default='pending', max_length=16, verbose_name='状态')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('resolved_note', models.TextField(blank=True, default='', verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '预警',
                'verbose_name_plural': '预警',
                'db_table': 'alert',
                'ordering': ['-created_at'],
            },
        ),
    ]
