# Generated by Django 5.2.12 on 2026-03-11 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('elders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='elder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='elders.elder', verbose_name='老人'),
        ),
    ]
