# Generated by Django 5.2.12 on 2026-03-12 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='健康咨询', max_length=128, verbose_name='会话标题')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='elders.elder', verbose_name='老人')),
            ],
            options={
                'verbose_name': '对话会话',
                'verbose_name_plural': '对话会话',
                'db_table': 'ai_chat_session',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', '系统'), ('user', '用户'), ('assistant', '助手')], max_length=16, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.chatsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': '对话消息',
                'verbose_name_plural': '对话消息',
                'db_table': 'ai_chat_message',
                'ordering': ['created_at'],
            },
        ),
    ]
