# Generated by Django 5.2.12 on 2026-03-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
    ]
