# Generated by Django 5.2.12 on 2026-03-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('sequence', models.IntegerField(help_text='1=上半年, 2=下半年', verbose_name='第几次')),
                ('check_date', models.DateField(verbose_name='体检日期')),
                ('hospital', models.CharField(blank=True, default='', max_length=128, verbose_name='体检机构')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='身高(cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='体重(kg)')),
                ('blood_pressure', models.CharField(blank=True, default='', max_length=32, verbose_name='血压')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='心率')),
                ('blood_sugar', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='血糖(mmol/L)')),
                ('blood_lipid', models.CharField(blank=True, default='', max_length=64, verbose_name='血脂')),
                ('liver_function', models.CharField(blank=True, default='', max_length=128, verbose_name='肝功能')),
                ('kidney_function', models.CharField(blank=True, default='', max_length=128, verbose_name='肾功能')),
                ('blood_routine', models.CharField(blank=True, default='', max_length=255, verbose_name='血常规')),
                ('urine_routine', models.CharField(blank=True, default='', max_length=255, verbose_name='尿常规')),
                ('ecg', models.CharField(blank=True, default='', max_length=128, verbose_name='心电图')),
                ('chest_xray', models.CharField(blank=True, default='', max_length=128, verbose_name='胸部X光')),
                ('b_ultrasound', models.CharField(blank=True, default='', max_length=255, verbose_name='B超')),
                ('vision', models.CharField(blank=True, default='', max_length=64, verbose_name='视力')),
                ('hearing', models.CharField(blank=True, default='', max_length=64, verbose_name='听力')),
                ('overall_result', models.TextField(blank=True, default='', verbose_name='综合结论')),
                ('doctor_advice', models.TextField(blank=True, default='', verbose_name='医生建议')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='checkup_reports/', verbose_name='体检报告')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '体检记录',
                'verbose_name_plural': '体检记录',
                'db_table': 'checkup',
                'ordering': ['-year', '-sequence'],
            },
        ),
    ]
