# Generated by Django 5.2.12 on 2026-03-11 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkup', '0001_initial'),
        ('elders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='elder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to='elders.elder', verbose_name='老人'),
        ),
        migrations.AlterUniqueTogether(
            name='checkup',
            unique_together={('elder', 'year', 'sequence')},
        ),
    ]
