# Generated by Django 5.2.12 on 2026-03-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkup',
            name='blood_pressure',
        ),
        migrations.AddField(
            model_name='checkup',
            name='diastolic_bp',
            field=models.IntegerField(blank=True, null=True, verbose_name='舒张压'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='systolic_bp',
            field=models.IntegerField(blank=True, null=True, verbose_name='收缩压'),
        ),
    ]
