# Generated by Django 5.1.15 on 2026-04-23 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0002_community_is_active'),
        ('elders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='活动名称')),
                ('summary', models.CharField(blank=True, default='', max_length=160, verbose_name='活动摘要')),
                ('content', models.TextField(blank=True, default='', verbose_name='活动介绍')),
                ('location', models.CharField(blank=True, default='', max_length=128, verbose_name='活动地点')),
                ('starts_at', models.DateTimeField(verbose_name='开始时间')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('max_participants', models.PositiveIntegerField(default=30, verbose_name='人数上限')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '社区活动',
                'verbose_name_plural': '社区活动',
                'db_table': 'care_activity',
                'ordering': ['-starts_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FamilyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('relation', models.CharField(choices=[('child', '子女'), ('spouse', '配偶'), ('sibling', '兄弟姐妹'), ('relative', '亲属'), ('neighbor', '邻居'), ('other', '其他')], default='child', max_length=20, verbose_name='关系')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主要联系人')),
                ('notes', models.CharField(blank=True, default='', max_length=160, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_contacts', to='elders.elder', verbose_name='老人')),
            ],
            options={
                'verbose_name': '家属联系人',
                'verbose_name_plural': '家属联系人',
                'db_table': 'care_family_contact',
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedicationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=80, verbose_name='药品名称')),
                ('dosage', models.CharField(blank=True, default='', max_length=64, verbose_name='剂量')),
                ('frequency', models.CharField(blank=True, default='', max_length=64, verbose_name='频次')),
                ('schedule_time', models.CharField(blank=True, default='', max_length=64, verbose_name='提醒时间')),
                ('instructions', models.TextField(blank=True, default='', verbose_name='服药说明')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('last_taken_at', models.DateTimeField(blank=True, null=True, verbose_name='最近确认服药时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_plans', to='elders.elder', verbose_name='老人')),
            ],
            options={
                'verbose_name': '用药计划',
                'verbose_name_plural': '用药计划',
                'db_table': 'care_medication_plan',
                'ordering': ['-is_active', 'medicine_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('service', '服务预约'), ('sos', '紧急求助')], default='service', max_length=20, verbose_name='请求类型')),
                ('service_kind', models.CharField(choices=[('home_visit', '上门探访'), ('escort', '陪诊陪护'), ('meal', '助餐服务'), ('repair', '维修协助'), ('other', '其他需求'), ('emergency', '紧急求助')], default='other', max_length=20, verbose_name='服务类型')),
                ('title', models.CharField(max_length=80, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='需求说明')),
                ('preferred_time', models.CharField(blank=True, default='', max_length=80, verbose_name='期望时间')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('urgency', models.CharField(choices=[('normal', '普通'), ('high', '加急'), ('critical', '紧急')], default='normal', max_length=20, verbose_name='紧急程度')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='处理状态')),
                ('response_note', models.TextField(blank=True, default='', verbose_name='处理反馈')),
                ('handled_by', models.CharField(blank=True, default='', max_length=64, verbose_name='处理人')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='community.community', verbose_name='社区')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='elders.elder', verbose_name='老人')),
            ],
            options={
                'verbose_name': '服务工单',
                'verbose_name_plural': '服务工单',
                'db_table': 'care_service_order',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', '已报名'), ('cancelled', '已取消')], default='registered', max_length=20, verbose_name='状态')),
                ('notes', models.CharField(blank=True, default='', max_length=160, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_registrations', to='elders.elder', verbose_name='老人')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='care.communityactivity', verbose_name='活动')),
            ],
            options={
                'verbose_name': '活动报名',
                'verbose_name_plural': '活动报名',
                'db_table': 'care_activity_registration',
                'ordering': ['-created_at'],
                'unique_together': {('activity', 'elder')},
            },
        ),
    ]
